spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://###:3306/webgis?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: ##
    password: ###

  redis:
    database: 0
    host: 127.0.0.1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl